# Generated by Django 5.1.3 on 2024-11-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_viiews',
            new_name='movie_views',
        ),
    ]
